apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: storage2-highwaytocloud
  title: storage2-highwaytocloud
  description: storage2-highwaytocloud
  tags:
    - aws
    - s3
    - storage
  annotations:
    highwaytocloud.io/tool: terraform
    highwaytocloud.io/service: create_s3_bucket
spec:
  type: storage
  owner: guest
  lifecycle: production
