apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: storage10-highwaytocloud
  title: storage10-highwaytocloud
  description: storage10-highwaytocloud
  tags:
    - aws
    - s3
    - storage
  annotations:
    highwaytocloud.io/tool: storage-aws
    highwaytocloud.io/service: create_remote_storage
spec:
  type: storage
  owner: guest
  lifecycle: production
