apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buclet-1263
  title: buclet-1263
  description: buclet-1263
  tags:
    - aws
    - s3
    - storage
  annotations:
    highwaytocloud.io/tool: terraform
    highwaytocloud.io/service: create_s3_bucket
spec:
  type: storage
  owner: guest
  lifecycle: production
