apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bucket1
  title: bucket1
  description: bucket1
  tags:
    - aws
    - s3
    - storage
  annotations:
    highwaytocloud.io/tool: storage-aws
    highwaytocloud.io/service: create_remote_storage
spec:
  type: storage
  owner: guest
  lifecycle: production
