apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: volume-123456
  title: volume 123456
  description: volume 123456
  tags:
    - aws
    - s3
    - storage
  annotations:
    highwaytocloud.io/tool: terraform
    highwaytocloud.io/service: create_s3_bucket
spec:
  type: storage
  owner: guest
  lifecycle: production
