apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: storage-50
  title: storage-50
  description: storage-50
  tags:
    - aws
    - s3
    - storage
  annotations:
    highwaytocloud.io/tool: crossplane
    highwaytocloud.io/service: create_s3_bucket
spec:
  type: storage
  owner: guest
  lifecycle: production
