apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-2
  title: test-2
  description: test-2
  tags:
    - aws
    - s3
    - storage
  annotations:
    highwaytocloud.io/tool: terraform
    highwaytocloud.io/service: create_s3_bucket
spec:
  type: storage
  owner: guest
  lifecycle: production
