apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bucket2-aws-highway-to-cloud
  title: bucket2-aws-highway-to-cloud
  description: bucket2-aws-highway-to-cloud
  tags:
    - aws
    - s3
    - storage
  annotations:
    highwaytocloud.io/tool: storage-aws
    highwaytocloud.io/service: create_remote_storage
spec:
  type: storage
  owner: guest
  lifecycle: production
