apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bucket1
  title: Customer Documents S3 Bucket
  description: Bucket S3 che contiene i documenti caricati dai clienti.
  technology: terraform
  tags:
    - aws
    - s3
    - storage
spec:
  type: s3-bucket
  owner: guest
  lifecycle: production