integrations:
  github:
    - host: github.com
    
catalog:
  # ABILITA I TEMPLATE A LIVELLO GLOBALE
  rules:
    - allow: [Component, System, API, Resource, Template, Group, User]

catalog:
  locations:
    - type: url
      target: https://github.com/tommyliverani/highway-to-cloud/blob/main/resources/**/catalog-info.yaml
    - type: url
      target: https://github.com/tommyliverani/highway-to-cloud/blob/main/templates/**/template.yaml
      rules:
        - allow: [Template]