integrations:
  github:
    - host: github.com

catalog:
  locations:
    - type: url
      target: https://github.com/tommyliverani/highway-to-cloud/blob/main/resources/**/catalog-info.yaml
    - type: url
      target: https://github.com/tommyliverani/highway-to-cloud/blob/main/backstage/templates/**/template.yaml