integrations:
  github:
    - host: github.com
  # ABILITA I TEMPLATE A LIVELLO GLOBALE
  

catalog:
  rules:
      - allow: [Component, System, API, Resource, Template, Group, User]
  locations:
    - type: url
      target: https://github.com/tommyliverani/highway-to-cloud/blob/main/resources/**/catalog-info.yaml
    - type: url
      target: https://github.com/tommyliverani/highway-to-cloud/blob/main/templates/**/template.yaml