version: '3.8'

services:
  backstage:
    image: ghcr.io/backstage/backstage:latest
    container_name: backstage-stateless
    volumes:
      - ./app-config.local.yaml:/app/app-config.local.yaml
    # SPIEGHIAMO A BACKSTAGE DI CARICARE IL TUO FILE LOCALE
    command: ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.local.yaml"]
    environment:
      NODE_ENV: development # Evita anche i fastidiosi messaggi di WARN sul localhost
      APP_CONFIG_permission_enabled: "false"
      APP_CONFIG_backend_auth_dangerouslyDisableDefaultAuthPolicy: "true"
      APP_CONFIG_backend_database_client: better-sqlite3
      APP_CONFIG_backend_database_connection: ":memory:"
      APP_CONFIG_app_baseUrl: http://localhost:3000
      APP_CONFIG_backend_baseUrl: http://localhost:7007
    ports:
      - "3000:3000"
      - "7007:7007"