apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: create-remote-storage
  title: Create remote storage
  description: Creates a remote storage to save and share files
  idpServiceId: create_s3_bucket

spec:
  owner: team-platform
  type: infrastructure

  parameters:
    - title: Storage configuration
      description: Remote storage configuration
      required:
        - name
      properties:

        name:
          title: Storage name
          type: string
          description: Unique name of the remote storage to create
          pattern: '^(?!xn--|sthree-|amzn-s3-demo-)[a-z0-9][a-z0-9-]{1,35}[a-z0-9]$'
          ui:help: '3-37 characters: lowercase letters, numbers and hyphens; must start and end with a letter or number.'
          ui:autofocus: true

        title:
          title: Title
          type: string
          description: Display name of the resource in the Backstage catalog

        description:
          title: Description
          type: string
          description: Short description of the resource

  steps:

    - id: run-template-workflow
      name: Run template workflow
      action: github:actions:dispatch

      input:
        repoUrl: github.com?owner=tommyliverani&repo=highway-to-cloud
        workflowId: template.yaml
        branchOrTagName: develop

        workflowInputs:

          service_id: create_s3_bucket
          parameters: ${{ parameters | dump }}

    - id: log-workflow-link
      name: Print GitHub Actions link

      action: debug:log

      input:
        message: >-
          GitHub Actions workflow triggered:
          https://github.com/tommyliverani/highway-to-cloud/actions/workflows/template.yaml




# 1) fetch delle variabili
# 2) template del metadata e del catalog info
# 3) template degli skeleton definiti nel metadata
# 4) deploy degli skeleton valorizzati
