apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-s3-bucket
  title: AWS S3 Create bucket
  description: Automatizza la creazione di un bucket S3 su AWS
spec:
  owner: team-platform
  type: infrastructure

  # 1. PARAMETRI DEL FORM UI
  parameters:
    - title: Dettagli del Bucket
      required:
        - bucketName
      properties:
        bucketName:
          title: Nome del Bucket S3
          type: string
          description: Verrà validato secondo le convenzioni AWS.

  # 2. STEP DI AUTOMAZIONE
  steps:
    # Passo A: Prendi lo scheletro di file dal tuo repository (es. un file .tf di base)
    - id: fetch-base
      name: Recupera lo skeleton Git
      action: fetch:template
      input:
        url: ./skeleton # Una cartella locale al template con i file di base
        values:
          bucketName: ${{ parameters.bucketName }}

    # Passo B: Fai il commit del file YAML (quello che abbiamo visto prima) nel repo GitHub
    - id: publish
      name: Pubblica su GitHub nel tuo repo 'highway-to-cloud'
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: "Infrastruttura per il bucket ${{ parameters.bucketName }}"
        repoUrl: 'github.com?repo=highway-to-cloud&owner=tommyliverani'
        branchName: 'main'

    # Passo C: Registra automaticamente la nuova Resource nel catalogo attuale
    - id: register
      name: Registra nel catalogo di Backstage
      action: catalog:register
      input:
        repoUrl: 'github.com?repo=highway-to-cloud&owner=tommyliverani'
        catalogInfoPath: '/resources/${{ parameters.bucketName }}/catalog-info.yaml'