apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: create-s3-bucket
  title: AWS S3 Create bucket
  description: Automatizza la creazione di un bucket S3 su AWS

spec:
  owner: team-platform
  type: infrastructure

  parameters:
    - title: Dettagli del Bucket
      required:
        - bucketName
      properties:
        bucketName:
          title: Nome del Bucket S3
          type: string
          description: Verrà validato secondo le convenzioni AWS.

  steps:

    - id: clone-resource-repo
      name: Clone resources repository
      action: fetch:plain
      input:
        url: https://github.com/tommyliverani/highway-to-cloud.git
        targetPath: ./resources
    
    - id: clone-template-repo
      name: Clone template repository
      action: fetch:plain
      input:
        url: https://github.com/tommyliverani/highway-to-cloud.git
        targetPath: ./templates

    - id: generate-bucket-files
      name: Generate bucket files
      action: fetch:template
      input:
        url: ./templates/s3_createBucket/bucket
        targetPath: ./resources/${{ parameters.bucketName }}
        values:
          bucketName: ${{ parameters.bucketName }}
    

    

    


    # - id: create-pr
    #   name: Creazione Pull Request
    #   action: publish:github:pull-request
    #   input:
    #     repoUrl: github.com?owner=tommyliverani&repo=highway-to-cloud
    #     branchName: feature/${{ context.task.id }}-${{ parameters.bucketName }}
    #     title: "Create S3 bucket ${{ parameters.bucketName }}"
    #     description: |
    #       Creata automaticamente da Backstage.
    #       Task: ${{ context.task.id }}