apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: create-s3-bucket
  title: AWS S3 Create bucket
  description: Automatizza la creazione di un bucket S3 su AWS

spec:
  owner: team-platform
  type: infrastructure

  _config:
    resource_repo_url: &resource_url "https://github.com/tommyliverani/highway-to-cloud.git"
    resource_repo_path: &resource_path "./resources"

  parameters:
    - title: Dettagli del Bucket
      required:
        - bucketName
      properties:
        bucketName:
          title: Nome del Bucket S3
          type: string
          description: Verrà validato secondo le convenzioni AWS.

  steps:

    - id: clone-remote-repo
      name: Clonazione repository Git
      action: git:clone
      input:
        url: *resource_url
        targetPath: *resource_path


    - id: create-local-branch
      name: Creazione branch locale
      action: shell:command
      input:
        command: |
          git checkout -b feature/${{ context.task.id }}-${{ parameters.bucketName }}
        workingDirectory: *resource_path