apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: "test-23r4r4m"
  title: "test-23r4r4m"
  description: "test-23r4r4m"
  idp_tool: terraform
  tags:
    - aws
    - s3
    - storage
spec:
  type: storage
  owner: guest
  lifecycle: production
