apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: create-remote-storage
  title: Create remote storage
  description: Automatizza la creazione di uno storage remoto

spec:
  owner: team-platform
  type: infrastructure

  parameters:
    - title: Dettagli dello Storage
      required:
        - name
        - title
        - templateId
      properties:
        name:
          title: Nome dello Storage
          type: string
          description: Deve corrispondere alla directory sotto resources/ da processare.
        title:
          title: Titolo dello Storage
          type: string
          description: Titolo leggibile usato nel catalogo Backstage.
        description:
          title: Descrizione
          type: string
          description: Descrizione opzionale della risorsa.

  steps:
    - id: run-templater-workflow
      name: Run templater workflow
      action: github:actions:dispatch
      input:
        repoUrl: github.com?owner=tommyliverani&repo=highway-to-cloud
        workflowId: templater.yaml
        branchOrTagName: main
        workflowInputs:
          operation_id: create_remote_storage
          resource_kind_id: s3_bucket
          resource_id: ${{ parameters.name }}
          backstage_params: >-
            {"name":"${{ parameters.name }}","title":"${{ parameters.title }}","description":"${{ parameters.description }}"}