apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: "storage2-highwaytocloud"
  title: "storage2-highwaytocloud"
  description: "storage2-highwaytocloud"
  idp_tool: terraform
  tags:
    - aws
    - s3
    - storage
spec:
  type: storage
  owner: guest
  lifecycle: production
