deploy: argo
argo_application: "kubernetes-cluster-cluster1-crossplane"
argocd_namespace: "argocd"
kubeconfig: "/home/tommy/Desktop/tommy/highway-to-cloud/infra/secrets/kubernetes-cluster-cluster1.yaml"
kubectl: "/usr/local/k3s/bin/kubectl"
