name: Hello World Semplice

# Permette l'avvio manuale (sia da pulsante GitHub che tramite le API di Backstage)
on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Stampa un saluto
        run: echo "Hello, World! La GitHub Action è partita correttamente da Backstage!"